[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "apscheduler>=3.10.4",
    "flask>=3.1.0",
    "gtts>=2.5.4",
    "telegram>=0.0.1",
]
